Create ja_jp.json to 1.20
vadis365/Mob-Grinding-Utils pull request #309
Opened 2024-12-05 08:27 UTC by twister716

2024-12-22 05:34 UTC, Anpan715 requested changes
いくつかの修正点と、間違った翻訳（行80）を挙げてあります。
確認をお願いします。

2024-12-22 05:34 UTC, Anpan715 commented on MobGrindingUtils/MobGrindingUtils/src/main/resources/assets/mob_grinding_utils/lang/ja_jp.json
> +  "mob_grinding_utils.jei.any_experience": "受け入れ: forge:experience",
JEI本家の表記に合わせて、「以下のすべてで:」のほうがいいのではないでしょうか。

2024-12-22 05:34 UTC, Anpan715 commented on MobGrindingUtils/MobGrindingUtils/src/main/resources/assets/mob_grinding_utils/lang/ja_jp.json
> +  "item.mob_grinding_utils.nutritious_chicken_feed": "栄養価の高いチキンフィード",
GMは「Genetically Modified（遺伝子組み換え）」の略称のため「遺伝子組み換えの○○」が正しいと思われます。
さらにここは個人的な観点ですが、和訳とするのであれば「チキンフィード」よりも「ニワトリのエサ」のほうが違和感がなく感じます。

2024-12-22 05:34 UTC, Anpan715 commented on MobGrindingUtils/MobGrindingUtils/src/main/resources/assets/mob_grinding_utils/lang/ja_jp.json
> +  "death.attack.spikes.player": "%1$sはスパイク%2$sに突き刺さった。",
ここはMobの攻撃などよってスパイクで死亡したプレイヤーのログなので、「*プレイヤー名*は*攻撃者*によってスパイクに突き落とされた」が正しいです。

2024-12-22 05:34 UTC, Anpan715 commented on MobGrindingUtils/MobGrindingUtils/src/main/resources/assets/mob_grinding_utils/lang/ja_jp.json
> +  "tooltip.chickenfeed_2": "ニワトリを使い捨て...",
個人的には、「ニワトリを犠牲に、」や「ニワトリを消費して、」が表現としてはわかりやすいかと思います。

2024-12-22 05:34 UTC, Anpan715 commented on MobGrindingUtils/MobGrindingUtils/src/main/resources/assets/mob_grinding_utils/lang/ja_jp.json
> +  "block.mob_grinding_utils.entity_spawner.tooltip_4": "経験値速度アップグレードとスポナーの高さ/幅アップグレードで強化。",
今までの表現に合わせ、「強化できます。」といった敬語のニュアンスが良いかと思います。

2024-12-22 05:34 UTC, Anpan715 commented on MobGrindingUtils/MobGrindingUtils/src/main/resources/assets/mob_grinding_utils/lang/ja_jp.json
> +  "block.mob_grinding_utils.xp_tap.tooltip_1": "タンクの側面に取り付けます。",
ここは日本語で分かりやすく表現するには「タンクの側面に取り付けることができ、」が良いかもしれません。

2024-12-22 05:34 UTC, Anpan715 commented on MobGrindingUtils/MobGrindingUtils/src/main/resources/assets/mob_grinding_utils/lang/ja_jp.json
> +  "block.mob_grinding_utils.spikes.tooltip_2": "スパイクで殺されたMobはプレイヤーキルとしてカウントされません。",
細かいですが、「プレイヤーキル」は「プレイヤーのキル」にした方が分かりやすいかと思います。

2024-12-22 05:34 UTC, Anpan715 commented on MobGrindingUtils/MobGrindingUtils/src/main/resources/assets/mob_grinding_utils/lang/ja_jp.json
> +  "block.mob_grinding_utils.wither_muffler": "ウィザーボス死亡音マフラー",
ウィザーボスのほうが原文には近いですが、日本人から見たときに違和感をなくすためには「ウィザー」とした良いかもしれません。
これは他の「ウィザーボス」と表現されているところも同様です。

2024-12-22 05:41 UTC, twister716 commented
ありがとうございます
修正致します

2024-12-25 12:19 UTC, Anpan715 approved these changes

2024-12-25 18:31 UTC, Flanks255 approved these changes

2024-12-25 18:31 UTC, merged